version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:14.5
    volumes:
      - pgdata:/var/lib/postgresql/data-main # it avoids conflicts with other volumens
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: main
    command: -p 5432

  indexer:
    container_name: indexer
    image: indexer:local
    build:
      context: ..
      dockerfile: apps/indexer/Dockerfile
    depends_on:
      - postgres
    restart: always
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/substrate-dapp?sslmode=disable

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin:

networks:
  default:
    name: substrate-dapp
