version: '3'

dotenv: ['.env']
silent: true

tasks:
  boot:
    cmds:
      - docker-compose up -d --build
      - task migrate

  reboot:
    cmds:
      - task down
      - task boot

  seed:
    cmds:
      - echo "not implemented"

  up:
    cmds:
      - docker-compose up -d --build

  down:
    cmds:
      - docker-compose down -v --remove-orphans

  migrate:
    cmds:
      - echo "not implemented"

  reload:
    cmds:
      - task down 
      - docker-compose up -d postgres
      - sleep 5 
      - docker-compose up -d --build 
      - docker-compose logs -f